//! XBRL financial-fact extractor.
//!
//! Not really a "form" — XBRL data is embedded in 10-K / 10-Q
//! periodic reports, with the structured facts in per-filing R-XX.xml
//! files generated by SEC's filing renderer. The old approach used
//! SEC's bulk FSNDS quarterly feed, but the URL pattern broke
//! mid-2024.
//!
//! ## Emits (Phase F17)
//!
//! - `processed/metric_fact.csv` — one row per tagged fact (tag,
//!   ddate, qtrs, uom, value, dimensional_context).
//!
//! ## Goalpost section
//!
//! See `kglite/datasets/sec/FEATURE_GOALPOST.md` §11 — XBRL.

use crate::error::Result;
use crate::layout::Workdir;
use crate::slicing::SliceSpec;

use super::super::identity::Identities;
use super::super::sinks::Sinks;
use super::FormReport;

/// TODO(F17): new R-file parser in `parsers/xbrl_rfile.rs`. The bulk
/// FSNDS feed approach (`parsers/fsnds.rs`) stays but won't be used
/// once F17 lands — keeping it for reference until then.
pub fn extract(
    _workdir: &Workdir,
    _slice: &SliceSpec,
    _sinks: &mut Sinks,
    _identities: &mut Identities,
    _extracted_at: &str,
) -> Result<FormReport> {
    Ok(FormReport::default())
}
