/*
 * kglite-c — C ABI for the kglite knowledge graph engine.
 *
 * Generated by cbindgen. Do NOT edit by hand. To regenerate:
 *   cargo build -p kglite-c
 * (the crate's build.rs runs cbindgen automatically).
 *
 * Conventions: see docs/rust/c-abi.md in the kglite repo.
 *   https://github.com/kkollsga/kglite/blob/main/docs/rust/c-abi.md
 */

#ifndef KGLITE_H_INCLUDED
#define KGLITE_H_INCLUDED

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/**
 * C-ABI-side error code. Variants 1-17 map by meaning to
 * [`kglite::api::KgErrorCode`]; variants 100+ are C-ABI-specific
 * (invalid UTF-8 at the boundary, null pointer, OOM — conditions
 * that don't have a corresponding `KgErrorCode` because they
 * can't arise from inside the engine).
 */
enum KgliteStatusCode
#if __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // __STDC_VERSION__ >= 202311L
 {
  KGLITE_STATUS_CODE_OK = 0,
  KGLITE_STATUS_CODE_CYPHER_SYNTAX = 1,
  KGLITE_STATUS_CODE_CYPHER_TIMEOUT = 2,
  KGLITE_STATUS_CODE_CYPHER_EXECUTION = 3,
  KGLITE_STATUS_CODE_CYPHER_TYPE_MISMATCH = 4,
  KGLITE_STATUS_CODE_SCHEMA = 5,
  KGLITE_STATUS_CODE_VALIDATION = 6,
  KGLITE_STATUS_CODE_EXPR = 7,
  KGLITE_STATUS_CODE_NODE_NOT_FOUND = 8,
  KGLITE_STATUS_CODE_CONNECTION_NOT_FOUND = 9,
  KGLITE_STATUS_CODE_PROPERTY_NOT_FOUND = 10,
  KGLITE_STATUS_CODE_FILE_NOT_FOUND = 11,
  KGLITE_STATUS_CODE_FILE_FORMAT = 12,
  KGLITE_STATUS_CODE_FILE_IO = 13,
  KGLITE_STATUS_CODE_INVALID_ARGUMENT = 14,
  KGLITE_STATUS_CODE_MISSING_ARGUMENT = 15,
  KGLITE_STATUS_CODE_INTERNAL = 16,
  /**
   * The query was cooperatively cancelled (a binding flipped the
   * cancel flag). Appended here (not renumbered into core's
   * declaration position) to keep the existing discriminants stable
   * across this ABI major version.
   */
  KGLITE_STATUS_CODE_CANCELLED = 17,
  /**
   * A write violated a declared integrity constraint (UNIQUE / NOT
   * NULL / NODE KEY). The write was rejected before touching
   * storage, so the graph is unchanged. Appended to keep the
   * existing discriminants stable across this ABI major version.
   */
  KGLITE_STATUS_CODE_CONSTRAINT_VIOLATION = 18,
  /**
   * Declaring a constraint failed because the stored data already
   * violates it. Deduplicate the node type, then re-declare.
   */
  KGLITE_STATUS_CODE_CONSTRAINT_CREATION_FAILED = 19,
  /**
   * An optimistic-concurrency commit lost its race: the graph advanced
   * between `begin()` and `commit()`, so nothing was applied. Retry the
   * whole transaction. Appended to keep the existing discriminants
   * stable across this ABI major version.
   */
  KGLITE_STATUS_CODE_TRANSACTION_CONFLICT = 20,
  /**
   * A `.kgl` load was refused *before decoding* because its estimated peak
   * memory exceeded the ceiling the caller set
   * (`LoadOptions::max_load_bytes` / `KGLITE_MAX_LOAD_MB`). The file is
   * valid; this process's budget is not. Its own code rather than a
   * `FileFormat` because the two call for opposite reactions — "rebuild this
   * file" versus "raise the ceiling, defer the index rebuild, or load it
   * somewhere larger" — and a consumer cannot tell them apart by
   * string-matching a message.
   *
   * Appended (not renumbered) to keep the existing discriminants stable
   * across this ABI major version.
   */
  KGLITE_STATUS_CODE_LOAD_MEMORY_LIMIT = 21,
  /**
   * A string argument failed UTF-8 validation. The C-side
   * caller passed a `*const c_char` whose bytes didn't decode
   * as UTF-8 — typically a corrupted buffer or a non-UTF-8
   * locale string. kglite is UTF-8 throughout.
   */
  KGLITE_STATUS_CODE_INVALID_UTF8 = 100,
  /**
   * A required pointer argument was null. The function
   * can't proceed; check your call site.
   */
  KGLITE_STATUS_CODE_NULL_POINTER = 101,
  /**
   * Another process (or another un-freed handle in this one) holds the
   * cross-process writer lease for that graph path, so
   * [`kglite_writer_lease_acquire`](crate::kglite_writer_lease_acquire)
   * gave up. The error message names the holder. Retriable as-is, which
   * is why it is its own code rather than a `FileIo`: "wait and try
   * again" and "the disk is broken" call for opposite reactions, and a
   * binding cannot tell them apart by string-matching a message.
   *
   * Appended (not renumbered) to keep the existing discriminants stable
   * across this ABI major version.
   */
  KGLITE_STATUS_CODE_WRITER_LEASE_HELD = 102,
};
#if __STDC_VERSION__ >= 202311L
typedef enum KgliteStatusCode KgliteStatusCode;
#else
typedef uint32_t KgliteStatusCode;
#endif // __STDC_VERSION__ >= 202311L

/**
 * The ABI version that this build of `kglite-c` exposes. Derived at
 * compile time from the crate's package version (`CARGO_PKG_VERSION_*`),
 * so it tracks the engine version automatically.
 */
typedef struct KgliteAbiVersion {
  uint32_t major;
  uint32_t minor;
  uint32_t patch;
} KgliteAbiVersion;

/**
 * The persisted-format version numbers this build reads and writes. Distinct
 * from [`KgliteAbiVersion`], which is the engine SemVer: this describes the
 * on-disk format lifecycle, so an embedder can report the storage version it
 * operates against and refuse a file it cannot read.
 */
typedef struct KgliteStorageFormat {
  /**
   * `.kgl` snapshot format version stamped into new saves.
   */
  uint32_t kgl;
  /**
   * Write-ahead-log frame format version this build writes.
   */
  uint32_t wal;
  /**
   * Oldest write-ahead-log frame format version this build can replay.
   */
  uint32_t min_readable_wal;
} KgliteStorageFormat;

/**
 * Rust-heap statistics from kglite's tracking allocator.
 */
typedef struct KgMemStats {
  /**
   * Current live Rust-heap bytes (allocated minus freed).
   */
  uint64_t current_bytes;
  /**
   * Peak live Rust-heap bytes since process start.
   */
  uint64_t peak_bytes;
  /**
   * Total number of allocations since process start (monotonic).
   */
  uint64_t total_allocs;
} KgMemStats;

/**
 * Opaque handle for an embedder. See
 * [`KgliteGraph`](crate::KgliteGraph) for the rationale on the
 * empty `#[repr(C)]` facade pattern — cbindgen renders only a
 * forward declaration; the actual state lives in
 * [`EmbedderState`].
 */
typedef struct KgliteEmbedder {
  uint8_t _opaque[0];
} KgliteEmbedder;

/**
 * Opaque handle for a session. See [`KgliteGraph`](crate::KgliteGraph)
 * for the rationale on the empty `#[repr(C)]` facade pattern.
 */
typedef struct KgliteSession {
  uint8_t _opaque[0];
} KgliteSession;

/**
 * Opaque handle for a knowledge graph. The C-side caller only
 * ever sees `KgliteGraph*`; allocation, deallocation, and field
 * access happen inside `kglite-c`.
 *
 * cbindgen sees the `#[repr(C)]` empty struct and renders only a
 * forward declaration in `kglite.h`. The actual state lives in
 * the private [`GraphState`] sidecar: every `*mut KgliteGraph`
 * the C side holds is really a `*mut GraphState` cast through
 * the opaque facade.
 */
typedef struct KgliteGraph {
  uint8_t _opaque[0];
} KgliteGraph;

/**
 * Opaque handle for a held writer lease. See
 * [`KgliteGraph`](crate::KgliteGraph) for the rationale on the empty
 * `#[repr(C)]` facade pattern — cbindgen renders only a forward
 * declaration; the actual state lives in [`LeaseState`].
 */
typedef struct KgliteWriterLease {
  uint8_t _opaque[0];
} KgliteWriterLease;

/**
 * Opaque handle for a Cypher result. See
 * [`KgliteGraph`](crate::KgliteGraph) for the rationale on the
 * empty `#[repr(C)]` facade pattern — cbindgen renders only a
 * forward declaration; the actual state lives in [`ResultState`].
 */
typedef struct KgliteCypherResult {
  uint8_t _opaque[0];
} KgliteCypherResult;

/**
 * Return the C ABI version this library was built against.
 * Bindings should call this on startup and refuse to proceed if
 * the major version doesn't match what they were compiled
 * against — a mismatched major risks segfaults from changed
 * struct layouts or removed functions.
 *
 * Conventions within a major version: additive only (new
 * functions, new status codes, new opaque types). Existing
 * function signatures and struct layouts never change.
 *
 * # Examples
 *
 * ```c
 * KgliteAbiVersion v = kglite_abi_version();
 * if (v.major != KGLITE_EXPECTED_MAJOR) {
 *     fprintf(stderr, "kglite ABI mismatch: expected %u.x, got %u.%u.%u\n",
 *                     KGLITE_EXPECTED_MAJOR, v.major, v.minor, v.patch);
 *     return 1;
 * }
 * ```
 */
 struct KgliteAbiVersion kglite_abi_version(void);

/**
 * Return the on-disk storage format versions this library reads and writes.
 *
 * The `.kgl` snapshot format (`kgl`) is the primary number a binding surfaces
 * as its persisted-format version; `wal` and `min_readable_wal` describe the
 * write-ahead-log frame format for a binding that needs the durability detail
 * too. All three are independent of the engine SemVer reported by
 * [`kglite_abi_version`] — a patch release can change the engine version
 * without touching any of these, and a format bump moves one of these without
 * implying an ABI-major change.
 *
 * # Examples
 *
 * ```c
 * KgliteStorageFormat f = kglite_storage_format_version();
 * printf("kgl format v%u, wal v%u (min readable v%u)\n",
 *        f.kgl, f.wal, f.min_readable_wal);
 * ```
 */
 struct KgliteStorageFormat kglite_storage_format_version(void);

/**
 * Return current Rust-heap statistics from kglite's tracking allocator.
 * Counts only allocations through the Rust global allocator — the host
 * runtime's own heap is separate. Useful for a binding to surface
 * kglite's memory footprint in its own metrics.
 */
 struct KgMemStats kglite_memory_stats(void);

/**
 * Free an embedder handle. Idempotent on null.
 *
 * # Safety
 *
 * `embedder` must be either null or a valid pointer previously
 * returned by a `kglite_embedder_*_new` factory and not yet
 * freed. Calling twice on the same pointer is UB.
 *
 * [`kglite_session_set_embedder`] borrows this handle and clones the inner
 * Arc. The caller retains ownership and must free the handle exactly once,
 * including after a successful attachment; the session's clone stays alive.
 */
 void kglite_embedder_free(struct KgliteEmbedder *embedder);

/**
 * Attach an embedder to a session. The session retains a clone
 * of the embedder's inner `Arc`, so subsequent
 * [`kglite_session_execute_read`](crate::kglite_session_execute_read)
 * calls have access to `text_score()` and other embedder-backed
 * Cypher functions.
 *
 * The caller may free the embedder handle after this call
 * returns — the `Arc` clone keeps the underlying embedder
 * alive for the session's lifetime.
 *
 * # Safety
 *
 * `session` and `embedder` must be valid handles previously
 * returned by `kglite_session_new` and a `kglite_embedder_*_new`
 * factory respectively, neither yet freed.
 */

KgliteStatusCode kglite_session_set_embedder(struct KgliteSession *session,
                                             const struct KgliteEmbedder *embedder);

#if defined(KGLITE_FEATURE_FASTEMBED)
/**
 * Construct a fastembed-rs-backed embedder.
 *
 * fastembed-rs downloads ONNX model weights on first
 * `embed()` call (cached at `~/.cache/fastembed/`). The factory
 * does NOT block on download — model name validation only. The
 * first Cypher query using `text_score()` triggers the download.
 *
 * # Arguments
 *
 * - `model_name` (in, borrowed): a known fastembed model name,
 *   e.g. `"BAAI/bge-m3"`, `"sentence-transformers/all-MiniLM-L6-v2"`.
 *   See fastembed-rs's TextEmbedding::list_supported_models() for
 *   the full list.
 * - `out_embedder` (out, owned): on success, set to an embedder
 *   handle. Caller must free via [`kglite_embedder_free`], including after
 *   attaching it with [`kglite_session_set_embedder`], which borrows it.
 * - `out_error_msg` (out, owned, may be null): on failure, set to
 *   an owned error string.
 *
 * # Errors
 *
 * - `KGLITE_STATUS_CODE_NULL_POINTER` — required pointer is null
 * - `KGLITE_STATUS_CODE_INVALID_UTF8` — `model_name` isn't valid UTF-8
 * - `KGLITE_STATUS_CODE_INVALID_ARGUMENT` — `model_name` isn't a known
 *   fastembed model
 *
 * # Feature gate
 *
 * Available only when `kglite-c` is built with the `fastembed`
 * Cargo feature.
 *
 * # Safety
 *
 * `model_name` must be a null-terminated UTF-8 string.
 * `out_embedder` must be a valid writable pointer.
 */

KgliteStatusCode kglite_embedder_fastembed_new(const char *model_name,
                                               struct KgliteEmbedder **out_embedder,
                                               const char **out_error_msg);
#endif

/**
 * Replace the embedding store for `(node_type, "{text_column}_emb")` with
 * `count` vectors keyed by the ids in `ids_json`.
 *
 * Wraps [`kglite::api::embeddings::set_embeddings`]: the store — dimension,
 * metric and provenance — is discarded and rebuilt, so this is the "these are
 * the vectors" call. Use [`kglite_session_add_embeddings`] to extend a store
 * across several batches.
 *
 * `vectors` is `dim * count` `f32`s, row-major: vector `i` is
 * `vectors[i*dim .. (i+1)*dim]`, aligned with id `i` in `ids_json`. An id that
 * matches no node of `node_type` is counted as `skipped`, never fatal. The
 * dimension is taken from the batch; every vector must share it. `metric` (may
 * be null) names the distance the store is scored with — `"cosine"`,
 * `"dot_product"`, `"euclidean"`, `"poincare"`; null scores with cosine.
 *
 * `count == 0` (or a null `vectors` with `count == 0`) is the empty batch: no
 * write, a zero report, no version bump. `ids_json` must always be a JSON array
 * of exactly `count` ids.
 *
 * On success `out_report_json` is an owned JSON object
 * `{"embeddings_stored": N, "dimension": D, "skipped": M, "store_created": true}`;
 * free it with [`kglite_free_string`](crate::kglite_free_string).
 *
 * # Errors
 *
 * - `KGLITE_ERR_NULL_POINTER` — `session`, `node_type`, `text_column`,
 *   `ids_json`, or `out_report_json` is null (or `vectors` is null with
 *   `count > 0`).
 * - `KGLITE_ERR_INVALID_UTF8` — a string argument is not valid UTF-8.
 * - `KGLITE_ERR_INVALID_ARGUMENT` — `ids_json` is not a JSON array of exactly
 *   `count` ids, `dim == 0` with `count > 0`, or the engine rejected the batch
 *   (unknown node type, inconsistent dimension, unknown metric); the message
 *   explains which.
 *
 * **The store is not durable until saved.** Embeddings are checkpoint-only;
 * call [`kglite_session_save`](crate::kglite_session_save) to persist them.
 *
 * # Safety
 *
 * `session` must be a valid handle from
 * [`kglite_session_new`](crate::kglite_session_new). `node_type`,
 * `text_column` and `ids_json` must be null-terminated UTF-8 strings; `metric`
 * null or the same. `vectors` must point to at least `dim * count` readable
 * `f32`s (unread when `count == 0`). `out_report_json` must be a valid writable
 * slot; `out_error_msg` null or a valid writable slot.
 */

KgliteStatusCode kglite_session_set_embeddings(struct KgliteSession *session,
                                               const char *node_type,
                                               const char *text_column,
                                               const char *ids_json,
                                               const float *vectors,
                                               uintptr_t dim,
                                               uintptr_t count,
                                               const char *metric,
                                               const char **out_report_json,
                                               const char **out_error_msg);

/**
 * Upsert `count` vectors into the store for `(node_type, "{text_column}_emb")`,
 * creating it if it does not exist yet.
 *
 * Wraps [`kglite::api::embeddings::add_embeddings`]: the incremental
 * counterpart to [`kglite_session_set_embeddings`]. Ids already in the store
 * replace their vector in place; the rest are appended. When the store already
 * exists its dimension is authoritative and every incoming vector must match
 * it; `metric` applies only to the call that creates the store.
 *
 * Parameters, buffer layout, empty-batch and durability semantics are
 * identical to [`kglite_session_set_embeddings`]. The report additionally
 * reports whether this call created the store:
 * `{"embeddings_stored": N, "dimension": D, "skipped": M, "store_created": B}`.
 *
 * # Errors
 *
 * Same as [`kglite_session_set_embeddings`].
 *
 * # Safety
 *
 * Same as [`kglite_session_set_embeddings`].
 */

KgliteStatusCode kglite_session_add_embeddings(struct KgliteSession *session,
                                               const char *node_type,
                                               const char *text_column,
                                               const char *ids_json,
                                               const float *vectors,
                                               uintptr_t dim,
                                               uintptr_t count,
                                               const char *metric,
                                               const char **out_report_json,
                                               const char **out_error_msg);

/**
 * Build an HNSW index over the store for `(node_type, "{text_column}_emb")`,
 * accelerating whole-corpus top-k vector search.
 *
 * Wraps [`kglite::api::embeddings::build_vector_index`]. Later vector writes
 * are folded into the index at query entry while the outstanding delta stays
 * under the engine default ceiling; a larger one serves the exact scan until
 * the index is rebuilt. `m`, `ef_construction` and `ef_search` use the engine
 * default when passed `0` and are clamped to their valid range otherwise. `metric` (may be null) resolves as explicit argument,
 * then the store's own metric, then cosine; `"cosine"`, `"dot_product"` and
 * `"euclidean"` are indexable, and `"poincare"` is rejected (its search stays
 * on the exact path).
 *
 * On success `out_report_json` is an owned JSON object
 * `{"indexed": N, "metric": "cosine", "m": M}`; free it with
 * [`kglite_free_string`](crate::kglite_free_string).
 *
 * # Errors
 *
 * - `KGLITE_ERR_NULL_POINTER` — `session`, `node_type`, `text_column`, or
 *   `out_report_json` is null.
 * - `KGLITE_ERR_INVALID_UTF8` — a string argument is not valid UTF-8.
 * - `KGLITE_ERR_INVALID_ARGUMENT` — no store to index, an unknown or
 *   non-indexable metric; the message explains which.
 *
 * # Safety
 *
 * `session` must be a valid handle from
 * [`kglite_session_new`](crate::kglite_session_new). `node_type` and
 * `text_column` must be null-terminated UTF-8 strings; `metric` null or the
 * same. `out_report_json` must be a valid writable slot; `out_error_msg` null
 * or a valid writable slot.
 */

KgliteStatusCode kglite_session_build_vector_index(struct KgliteSession *session,
                                                   const char *node_type,
                                                   const char *text_column,
                                                   uintptr_t m,
                                                   uintptr_t ef_construction,
                                                   uintptr_t ef_search,
                                                   const char *metric,
                                                   const char **out_report_json,
                                                   const char **out_error_msg);

/**
 * List every embedding store on the session's graph.
 *
 * A read-only projection of the graph's embedding stores — the C companion to
 * the Python `list_embeddings()`. Reads a snapshot, so it takes no write lock
 * and never forks.
 *
 * On success `out_report_json` is an owned JSON array, one object per store:
 * `{"node_type": "Note", "text_column": "body", "dimension": 384,
 *   "count": 1000, "metric": "cosine"}`. `text_column` is the source column
 * (the store's `"_emb"` suffix stripped), and `metric` is the store's own
 * metric or `"cosine"` when it recorded none. Free it with
 * [`kglite_free_string`](crate::kglite_free_string). A graph with no stores
 * returns `"[]"`.
 *
 * # Errors
 *
 * - `KGLITE_ERR_NULL_POINTER` — `session` or `out_report_json` is null.
 *
 * # Safety
 *
 * `session` must be a valid handle from
 * [`kglite_session_new`](crate::kglite_session_new). `out_report_json` must be
 * a valid writable slot; `out_error_msg` null or a valid writable slot.
 */

KgliteStatusCode kglite_session_list_embeddings(const struct KgliteSession *session,
                                                const char **out_report_json,
                                                const char **out_error_msg);

/**
 * Create a new, empty in-memory knowledge graph.
 *
 * The returned handle owns a fresh, empty `DirGraph` — the C-side
 * analogue of constructing `KnowledgeGraph()` in Python. Build it up
 * by opening a session ([`kglite_session_new`](crate::kglite_session_new))
 * and running `CREATE` / `MERGE` Cypher through
 * [`kglite_session_execute_mut`](crate::kglite_session_execute_mut), or
 * by bulk-loading via the blueprint entry point. Before this
 * existed, the only way to obtain a graph at the C boundary was to load
 * a pre-built `.kgl` file — a binding could not start one from scratch.
 *
 * # Returns
 *
 * A non-null `KgliteGraph*` the caller must free with
 * [`kglite_graph_free`], or hand to
 * [`kglite_session_new`](crate::kglite_session_new) which takes
 * ownership. Returns null only on allocation failure.
 */
 struct KgliteGraph *kglite_graph_new(void);

/**
 * Create a fresh, empty knowledge graph in an explicit storage mode.
 *
 * `mode` is `"memory"` (alias `"default"`), `"mapped"`, or `"disk"` — the
 * same mode vocabulary as Python's `storage=` argument:
 *
 * - `"memory"` — heap-resident (the default; same as [`kglite_graph_new`]).
 * - `"mapped"` — property columns spill to mmap during build, so a graph
 *   larger than RAM can be constructed; saves to a `.kgl` file.
 * - `"disk"` — CSR + mmap on-disk directory format for very large graphs;
 *   **requires** `path` (the directory that becomes the graph).
 *
 * This is the create/ingest entry point. Opening an existing graph
 * ([`kglite_load_file`]) auto-detects its mode, so no mode argument is
 * needed there.
 *
 * # Arguments
 *
 * - `mode` (in, borrowed): UTF-8 mode string, null-terminated.
 * - `path` (in, borrowed): UTF-8 directory path for `"disk"`, else null.
 * - `out_graph` (out, owned): set to the new graph handle on success
 *   (free via [`kglite_graph_free`], or hand to
 *   [`kglite_session_new`](crate::kglite_session_new)); null on failure.
 * - `out_error_msg` (out, owned): owned error message on failure (free via
 *   [`kglite_free_string`](crate::kglite_free_string)); null on success.
 *
 * # Errors
 *
 * - `KGLITE_ERR_NULL_POINTER` — `mode` or `out_graph` is null
 * - `KGLITE_ERR_INVALID_UTF8` — `mode` / `path` isn't valid UTF-8
 * - `KGLITE_ERR_INVALID_ARGUMENT` — unknown mode, or `"disk"` with no path
 * - `KGLITE_ERR_FILE_IO` — failed to create the disk-graph directory
 *
 * # Safety
 *
 * `mode` must be a null-terminated UTF-8 string; `path` null or the same;
 * `out_graph` a valid `*mut KgliteGraph` slot; `out_error_msg` null or a
 * valid slot.
 */

KgliteStatusCode kglite_graph_new_in_mode(const char *mode,
                                          const char *path,
                                          struct KgliteGraph **out_graph,
                                          const char **out_error_msg);

/**
 * Report the storage mode a graph is in **right now**.
 *
 * The counterpart of the mode a checkpoint *recorded*: this is the backend the
 * handle is actually running on, after any conversion
 * [`kglite_open_or_create_graph_in_mode`](crate::kglite_open_or_create_graph_in_mode)
 * performed. That function's `out_converted_from` answers "what was it
 * before?" and is null whenever nothing changed; this answers "what is it
 * now?" unconditionally — the question a binding has to ask after creating a
 * graph, after an unspecified-mode open, or to assert that the mode it asked
 * for is the mode it got. Without it the only route to the answer was to infer
 * it from a conversion report, which says nothing when no conversion happened.
 *
 * Reads the same classification (`live_storage_mode`) the wheel's
 * `graph_info()["storage_mode"]` and the servers' `--storage` check report, so
 * the modes cannot drift between bindings.
 *
 * # Arguments
 *
 * - `graph` (in, borrowed): the graph handle. **Not** consumed — the caller
 *   still owns it and may hand it to
 *   [`kglite_session_new`](crate::kglite_session_new) afterwards.
 * - `out_mode` (out, owned): set to `"memory"`, `"mapped"` or `"disk"` — the
 *   same mode vocabulary [`kglite_graph_new_in_mode`] accepts. Free via
 *   [`kglite_free_string`](crate::kglite_free_string).
 * - `out_error_msg` (out, owned): null or a valid slot; set to null here,
 *   since the only failure is a null-argument one with nothing to describe.
 *
 * # Errors
 *
 * - `KGLITE_ERR_NULL_POINTER` — `graph` or `out_mode` is null
 *
 * # Safety
 *
 * `graph` must be a valid `*mut KgliteGraph` not yet freed or moved into a
 * session; `out_mode` a valid writable `*const c_char` slot; `out_error_msg`
 * null or a valid slot.
 */

KgliteStatusCode kglite_graph_storage_mode(struct KgliteGraph *graph,
                                           const char **out_mode,
                                           const char **out_error_msg);

/**
 * Load a knowledge graph from disk. Accepts `.kgl` files
 * (single-file mmap format) and directories (disk-backed CSR
 * layout) — the loader picks the right path based on what's at
 * `path`.
 *
 * # Arguments
 *
 * - `path` (in, borrowed): UTF-8 file path, null-terminated.
 * - `out_graph` (out, owned): set to the loaded graph handle on
 *   success; caller must free via [`kglite_graph_free`]. Set to
 *   null on failure.
 * - `out_error_msg` (out, owned): set to an owned error message
 *   on failure; caller must free via
 *   [`kglite_free_string`](crate::kglite_free_string). Set to
 *   null on success.
 *
 * # Errors
 *
 * - `KGLITE_ERR_NULL_POINTER` — `path` or `out_graph` is null
 * - `KGLITE_ERR_INVALID_UTF8` — `path` isn't valid UTF-8
 * - `KGLITE_ERR_FILE_NOT_FOUND` — `path` doesn't exist
 * - `KGLITE_ERR_FILE_FORMAT` — file isn't a valid `.kgl` /
 *   disk-graph directory
 * - `KGLITE_ERR_FILE_IO` — I/O failure during read
 *
 * # Safety
 *
 * `path` must point to a null-terminated UTF-8 string.
 * `out_graph` must be a valid writable pointer to a
 * `*mut KgliteGraph` slot. `out_error_msg` may be null (the
 * caller doesn't care about the message); otherwise it must
 * point to a valid writable `*const c_char` slot.
 */

KgliteStatusCode kglite_load_file(const char *path,
                                  struct KgliteGraph **out_graph,
                                  const char **out_error_msg);

#if defined(KGLITE_FEATURE_RDF)
/**
 * Load an RDF file into a fresh in-memory graph — the C-side handle on
 * the wheel's `kglite.load_rdf`. Dispatches on the extension: `.ttl`
 * (Turtle), `.nt` (N-Triples), `.nq` (N-Quads), `.trig` (TriG).
 *
 * The RDF → property-graph fold: object literals become typed node
 * properties, resource objects become edges, and `rdf:type` sets the
 * node label (first wins; extras kept in an `rdf_types` property).
 * Predicate / type IRIs are CURIE-compacted with a `__` separator
 * (so `[:foaf__knows]` matches in Cypher); each node keeps its full
 * subject IRI in a `uri` property. In-memory backend only.
 *
 * # Arguments
 *
 * - `path` (in, borrowed): UTF-8 file path; the extension picks the parser.
 * - `languages_json` (in, borrowed): JSON array of language tags to keep
 *   (e.g. `["en","de"]`), or null to keep all literals.
 * - `label_predicates_json` (in, borrowed): JSON array of predicate IRIs
 *   whose literal object sets the node title, or null for
 *   `["http://www.w3.org/2000/01/rdf-schema#label"]`.
 * - `keep_full_iris` (in): non-zero keeps full IRIs instead of CURIEs.
 * - `default_type` (in, borrowed): node type for subjects without an
 *   `rdf:type`, or null for `"Resource"`.
 * - `max_triples` (in): stop after this many triples; negative = no limit.
 * - `out_graph` (out, owned): the loaded graph on success (free via
 *   [`kglite_graph_free`] or hand to
 *   [`kglite_session_new`](crate::kglite_session_new)); null on failure.
 * - `out_stats_json` (out, owned): `{"nodes":N,"edges":M,"triples":T}` on
 *   success — free via [`kglite_free_string`](crate::kglite_free_string).
 *   May be null if the caller doesn't want stats.
 * - `out_error_msg` (out, owned): error message on failure — free via
 *   [`kglite_free_string`](crate::kglite_free_string); null on success.
 *
 * # Errors
 *
 * - `KGLITE_ERR_NULL_POINTER` — `path` or `out_graph` is null
 * - `KGLITE_ERR_INVALID_UTF8` — a string argument isn't valid UTF-8
 * - `KGLITE_ERR_INVALID_ARGUMENT` — a `*_json` arg isn't a JSON string
 *   array, or the file extension isn't a supported RDF format
 * - `KGLITE_ERR_FILE_NOT_FOUND` — `path` doesn't exist
 * - `KGLITE_ERR_FILE_FORMAT` — a parse error in the RDF
 *
 * # Safety
 *
 * String arguments must each be a null-terminated UTF-8 string or null;
 * `out_graph` a valid writable `*mut KgliteGraph` slot; `out_stats_json`
 * and `out_error_msg` null or valid writable slots.
 */

KgliteStatusCode kglite_load_rdf(const char *path,
                                 const char *languages_json,
                                 const char *label_predicates_json,
                                 uint8_t keep_full_iris,
                                 const char *default_type,
                                 int64_t max_triples,
                                 struct KgliteGraph **out_graph,
                                 const char **out_stats_json,
                                 const char **out_error_msg);
#endif

/**
 * Save a knowledge graph to disk. The on-disk format depends on
 * the underlying storage mode — in-memory and mapped graphs
 * produce a `.kgl` single-file; disk-backed graphs produce / fill
 * a directory.
 *
 * The write is atomic (temp + rename) and **durable** (file +
 * parent-directory fsync) — a crash mid-save can't tear the file.
 * Use [`kglite_save_graph_durable`] with `fsync == 0` for the fast,
 * non-durable opt-out.
 *
 * # Arguments
 *
 * - `graph` (in, borrowed): the graph to save.
 * - `path` (in, borrowed): UTF-8 destination path,
 *   null-terminated.
 * - `out_error_msg` (out, owned): set to an owned error message
 *   on failure; caller must free via
 *   [`kglite_free_string`](crate::kglite_free_string). Set to
 *   null on success.
 *
 * # Errors
 *
 * - `KGLITE_ERR_NULL_POINTER` — `graph` or `path` is null
 * - `KGLITE_ERR_INVALID_UTF8` — `path` isn't valid UTF-8
 * - `KGLITE_ERR_FILE_IO` — write failed
 *
 * # Safety
 *
 * `graph` must be a valid `*mut KgliteGraph` previously returned
 * by a `kglite_*` function and not yet freed. `path` must be a
 * null-terminated UTF-8 string.
 */

KgliteStatusCode kglite_save_graph(struct KgliteGraph *graph,
                                   const char *path,
                                   const char **out_error_msg);

/**
 * Free a graph handle. Idempotent on null (no-op).
 *
 * # Safety
 *
 * `graph` must be either null or a pointer previously returned by
 * [`kglite_load_file`] (or any future `kglite_*` function that
 * returns a `*mut KgliteGraph`) and not yet freed. Calling twice
 * on the same pointer is UB.
 *
 * **Do NOT free** a graph handle that has been handed to
 * [`kglite_session_new`](crate::kglite_session_new) — the session
 * takes ownership and frees on its own teardown.
 */
 void kglite_graph_free(struct KgliteGraph *graph);

/**
 * Generate a synthetic benchmark/demo graph as CSVs + a manifest under
 * `out_dir`, in bounded memory. Load the result with [`kglite_load_file`]
 * pointed at `out_dir` — the C-side handle on `kglite.graphgen(...)`, the
 * "hello, query a graph" data source for a fresh binding.
 *
 * `zipf` != 0 uses a Zipf degree distribution (high-degree hubs) with
 * exponent `zipf_exp`; `zipf` == 0 uses uniform degree.
 *
 * On success `out_stats_json` is set to an owned `{"nodes": N, "edges": M}`
 * string — free via [`kglite_free_string`](crate::kglite_free_string).
 *
 * # Safety
 *
 * `out_dir` must be a null-terminated UTF-8 path; `out_stats_json` a valid
 * writable `*const c_char` slot; `out_error_msg` null or a valid slot.
 */

KgliteStatusCode kglite_graphgen_to_dir(uint64_t persons,
                                        uint64_t knows_per,
                                        uint64_t seed,
                                        uint8_t zipf,
                                        double zipf_exp,
                                        const char *out_dir,
                                        const char **out_stats_json,
                                        const char **out_error_msg);

/**
 * Build a graph declaratively from a blueprint file + a directory of
 * CSVs — the C-side handle on the wheel's `from_blueprint`. Loads the
 * JSON/YAML blueprint at `blueprint_path`, builds into a fresh graph
 * reading CSVs relative to `csv_dir`, and returns the populated graph.
 *
 * On success `out_graph` is set to a `KgliteGraph*` (free via
 * [`kglite_graph_free`] or hand to [`kglite_session_new`](crate::kglite_session_new)),
 * and `out_report_json` to an owned
 * `{"nodes_by_type":{..},"edges_by_type":{..},"warnings":[..],"errors":[..],"provisional_purged":N}`
 * string — free via [`kglite_free_string`](crate::kglite_free_string).
 *
 * # Safety
 *
 * `blueprint_path` / `csv_dir` must be null-terminated UTF-8 paths;
 * `out_graph` / `out_report_json` valid writable slots; `out_error_msg`
 * null or a valid slot.
 */

KgliteStatusCode kglite_blueprint_build(const char *blueprint_path,
                                        const char *csv_dir,
                                        struct KgliteGraph **out_graph,
                                        const char **out_report_json,
                                        const char **out_error_msg);

/**
 * Save a graph to a `.kgl` file with an explicit durability choice.
 *
 * `fsync` != 0 is exactly [`kglite_save_graph`]: mode-aware (disk dir vs
 * in-memory `.kgl`), atomic temp+rename, and the file + parent directory
 * are flushed to stable storage before returning — durable across power
 * loss, at the cost of fsync latency.
 *
 * `fsync` == 0 is the fast, **non-durable** opt-out: same mode-aware
 * atomic rename (never a torn file) but the fsync barrier is skipped, so
 * the bytes may not survive an OS/power crash. Use it only for bulk or
 * throwaway saves where you'll re-save or can rebuild.
 *
 * # Safety
 *
 * `graph` must be a valid handle; `path` a null-terminated UTF-8 path;
 * `out_error_msg` null or a valid slot.
 */

KgliteStatusCode kglite_save_graph_durable(struct KgliteGraph *graph,
                                           const char *path,
                                           uint8_t fsync,
                                           const char **out_error_msg);

/**
 * Serialize a graph to an in-memory `.kgl` byte buffer (no file). On
 * success `*out_buf` / `*out_len` describe an owned buffer the caller
 * MUST free with [`kglite_free_bytes`]. Pair with
 * [`kglite_graph_from_bytes`] to round-trip a graph through bytes (IPC,
 * object storage, …).
 *
 * # Safety
 *
 * `graph` valid; `out_buf` a valid `*mut u8` slot; `out_len` a valid
 * `usize` slot; `out_error_msg` null or valid.
 */

KgliteStatusCode kglite_graph_to_bytes(struct KgliteGraph *graph,
                                       uint8_t **out_buf,
                                       uintptr_t *out_len,
                                       const char **out_error_msg);

/**
 * Free a byte buffer returned by [`kglite_graph_to_bytes`]. Pass the
 * same `buf` / `len` pair. Null `buf` is a no-op.
 *
 * # Safety
 *
 * `buf` / `len` must be a pair previously returned by
 * [`kglite_graph_to_bytes`] and not yet freed.
 */
 void kglite_free_bytes(uint8_t *buf, uintptr_t len);

/**
 * Load a graph from an in-memory `.kgl` byte buffer — the inverse of
 * [`kglite_graph_to_bytes`].
 *
 * # Safety
 *
 * `data` / `len` must describe a readable buffer; `out_graph` a valid
 * writable slot; `out_error_msg` null or a valid slot.
 */

KgliteStatusCode kglite_graph_from_bytes(const uint8_t *data,
                                         uintptr_t len,
                                         struct KgliteGraph **out_graph,
                                         const char **out_error_msg);

/**
 * Compute a JSON schema overview of a graph: node types (count +
 * property types), connection types (endpoints + property names),
 * indexes, and total node/edge counts. The C-side handle on the
 * agent-facing schema — call it right after load / build / from_bytes
 * to learn a graph's shape before querying.
 *
 * On success `out_json` is set to an owned JSON object — free via
 * [`kglite_free_string`](crate::kglite_free_string). Operates on a graph
 * handle (before it is moved into a session).
 *
 * # Safety
 *
 * `graph` must be a valid handle; `out_json` a valid writable slot;
 * `out_error_msg` null or a valid slot.
 */

KgliteStatusCode kglite_compute_schema_json(struct KgliteGraph *graph,
                                            const char **out_json,
                                            const char **out_error_msg);

/**
 * Take the cross-process single-writer lease for a graph path.
 *
 * **The contract: any caller that may `save` to a path must hold this lease
 * across the whole read-modify-save interval. Readers need none.** The
 * window that loses a writer's work is open-to-save, not save itself — two
 * processes that both load a graph, both mutate, and both save produce two
 * complete snapshots, and the second one published wins outright, silently —
 * locking at save time is already too late. Acquire before the open, free
 * after the save.
 *
 * The lease is a pair of sidecar files next to `path` (`<path>.lock` holds
 * the OS lock, `<path>.lock-owner` records who has it). The OS releases the
 * lock when the holding process exits — including on a crash — so a lock
 * file left behind is not a stale lease, and deleting it does not release
 * anything.
 *
 * # Arguments
 *
 * - `path` (in, borrowed): UTF-8 graph path, null-terminated. The path need
 *   not exist yet; a caller creating a new graph takes the lease first.
 * - `timeout_ms` (in): how long to keep retrying a contended lease. **`0`
 *   is fail-fast** — return immediately if someone else holds it, because a
 *   blocked-for-30s open is a worse failure than a clear error. A caller that
 *   wants to queue passes a budget instead.
 * - `out_lease` (out, owned): set to the lease handle on success; the caller
 *   MUST free it with [`kglite_writer_lease_free`]. Null on failure.
 * - `out_error_msg` (out, owned): owned error message on failure (free via
 *   [`kglite_free_string`](crate::kglite_free_string)); null on success. On
 *   `KGLITE_STATUS_CODE_WRITER_LEASE_HELD` the message names the holding
 *   process (pid, and when it took the lease).
 *
 * # Errors
 *
 * - `KGLITE_ERR_NULL_POINTER` — `path` or `out_lease` is null
 * - `KGLITE_ERR_INVALID_UTF8` — `path` isn't valid UTF-8
 * - `KGLITE_STATUS_CODE_WRITER_LEASE_HELD` — someone else holds it; the
 *   message names them. Retriable as-is.
 * - `KGLITE_ERR_FILE_IO` / `KGLITE_ERR_FILE_NOT_FOUND` — the lock sidecar
 *   could not be created (unwritable or missing parent directory)
 *
 * # Safety
 *
 * `path` must be a null-terminated UTF-8 string; `out_lease` a valid
 * writable `*mut KgliteWriterLease` slot; `out_error_msg` null or a valid
 * writable slot.
 */

KgliteStatusCode kglite_writer_lease_acquire(const char *path,
                                             uint64_t timeout_ms,
                                             struct KgliteWriterLease **out_lease,
                                             const char **out_error_msg);

/**
 * [`kglite_writer_lease_acquire`], plus the holder as **JSON** rather than
 * only inside the message's prose.
 *
 * A binding that wants to surface the holding pid — the Java wrapper's
 * `holder()`, an operator dashboard, a retry policy that backs off longer for
 * a lease taken hours ago — otherwise has to regex a sentence written for
 * humans, and re-parse it every time the wording improves.
 *
 * Additive: `kglite_writer_lease_acquire` is unchanged and stays supported.
 * New callers should prefer this one.
 *
 * # Arguments
 *
 * Identical to [`kglite_writer_lease_acquire`], plus:
 *
 * - `out_holder_json` (out, owned): on
 *   `KGLITE_STATUS_CODE_WRITER_LEASE_HELD`, an owned JSON object (free via
 *   [`kglite_free_string`](crate::kglite_free_string)); null on every other
 *   outcome, including success. May itself be null if the caller does not
 *   want the detail. The object is:
 *
 *   ```json
 *   {"pid": 4711, "since": "2026-08-15T09:12:03+02:00",
 *    "self": false, "message": "…the same prose out_error_msg carries…"}
 *   ```
 *
 *   `pid` and `since` are `null` when the holder's record could not be read
 *   — it is published just *after* the lock is taken, so a contender losing
 *   a startup race can see an empty one. `self` is true when the holder is
 *   the calling process itself (an un-closed handle in the caller's own
 *   code, not another deployment), which is a different remedy and so is
 *   reported as its own field rather than left for a pid comparison the
 *   caller may forget to make.
 *
 * # Safety
 *
 * As [`kglite_writer_lease_acquire`]; `out_holder_json` must be null or a
 * valid writable slot.
 */

KgliteStatusCode kglite_writer_lease_acquire_ex(const char *path,
                                                uint64_t timeout_ms,
                                                struct KgliteWriterLease **out_lease,
                                                const char **out_holder_json,
                                                const char **out_error_msg);

/**
 * Release a writer lease and free its handle. Idempotent on null (no-op).
 *
 * This is the whole release protocol: there is no separate "unlock" call.
 * A handle that is never freed holds the lease for the life of the process —
 * the C-side shape of the Rust `Drop` that backs it — so a binding should
 * tie this call to its own deterministic teardown (`close()`, try-with-
 * resources, `defer`), not to a finalizer that may never run.
 *
 * # Safety
 *
 * `lease` must be either null or a pointer previously returned by
 * [`kglite_writer_lease_acquire`] or [`kglite_writer_lease_acquire_ex`] and
 * not yet freed. Calling twice on the same pointer is UB.
 */
 void kglite_writer_lease_free(struct KgliteWriterLease *lease);

/**
 * Open the graph at `path`, creating it when the path is absent, honouring
 * `mode` on **both** branches: a missing path is created in it, and an
 * existing graph that came back in a different mode is converted to it.
 *
 * This is the entry point for a binding that took a mode from *its* user
 * (the servers' `--storage`, the wheel's `storage=`). Pass `mode` null to
 * leave the decision to the graph: an existing checkpoint reopens in the
 * mode it recorded, and a missing path is an error rather than a silent
 * creation in some default. That asymmetry is deliberate — a mode argument
 * that also silently converted an existing graph would undo what the
 * checkpoint recorded, and a null one that silently created a graph would
 * turn a typo'd path into an empty database.
 *
 * A conversion is *reported*, through `out_converted_from`, never performed
 * silently — a silent conversion is as hard to notice as a silently ignored
 * flag. Conversions with no in-place transition (either disk direction) fail
 * with the reason and the alternative named.
 *
 * This function makes a lifecycle decision, **not** a write-ownership
 * promise. A caller that may later save to `path` must hold
 * [`kglite_writer_lease_acquire`]'s lease across the read-modify-save
 * interval; a read-only caller should not take one.
 *
 * # Arguments
 *
 * - `path` (in, borrowed): UTF-8 graph path (a `.kgl` file or a disk-graph
 *   directory), null-terminated.
 * - `mode` (in, borrowed, may be null): `"memory"` (alias `"default"`),
 *   `"mapped"`, or `"disk"` — the same mode vocabulary as
 *   [`kglite_graph_new_in_mode`](crate::kglite_graph_new_in_mode) and
 *   Python's `storage=`. **Null means unspecified**, the C spelling of "no
 *   mode argument at all".
 * - `out_graph` (out, owned): the opened / created graph on success (free
 *   via [`kglite_graph_free`](crate::kglite_graph_free), or hand to
 *   [`kglite_session_new`](crate::kglite_session_new)); null on failure.
 * - `out_converted_from` (out, owned, may be null): set to the mode the
 *   graph was in *before* an explicit `mode` converted it (`"memory"` /
 *   `"mapped"` / `"disk"`) — free via
 *   [`kglite_free_string`](crate::kglite_free_string). **Null when nothing
 *   was converted**, which is every open that already matched, every
 *   creation, and every unspecified-mode open.
 * - `out_error_msg` (out, owned): owned error message on failure; null on
 *   success.
 *
 * # Errors
 *
 * - `KGLITE_ERR_NULL_POINTER` — `path` or `out_graph` is null
 * - `KGLITE_ERR_INVALID_UTF8` — `path` / `mode` isn't valid UTF-8
 * - `KGLITE_ERR_FILE_NOT_FOUND` — the path is absent and `mode` was null,
 *   so there was no mode to create it in
 * - `KGLITE_ERR_INVALID_ARGUMENT` — unknown mode string, or a conversion
 *   that cannot happen in place (either disk direction)
 * - `KGLITE_ERR_FILE_FORMAT` / `KGLITE_ERR_FILE_IO` — as
 *   [`kglite_load_file`](crate::kglite_load_file)
 *
 * # Safety
 *
 * `path` must be a null-terminated UTF-8 string; `mode` null or the same;
 * `out_graph` a valid writable `*mut KgliteGraph` slot; `out_converted_from`
 * and `out_error_msg` null or valid writable slots.
 */

KgliteStatusCode kglite_open_or_create_graph_in_mode(const char *path,
                                                     const char *mode,
                                                     struct KgliteGraph **out_graph,
                                                     const char **out_converted_from,
                                                     const char **out_error_msg);

/**
 * Return the column names as a JSON array string:
 * `["col1", "col2", ...]`.
 *
 * The returned string is OWNED by the caller and must be freed
 * via [`kglite_free_string`](crate::kglite_free_string). Returns
 * null on serialization failure (shouldn't happen — column names
 * are always serializable).
 *
 * # Safety
 *
 * `result` must be null or a live pointer returned by a kglite query
 * function. It must not be freed while this call is running.
 */
 const char *kglite_cypher_result_columns_json(const struct KgliteCypherResult *result);

/**
 * Return all rows as a JSON array of objects keyed by column
 * name: `[{"col1": v1, "col2": v2}, ...]`.
 *
 * Cell values are **natural** JSON (`2`, `"x"`, `[..]`, `{..}`) via
 * [`kglite_value_to_json`](kglite::api::param::kglite_value_to_json) —
 * not serde's externally-tagged enum encoding — so a binding parses
 * `{"n": 2}`, not `{"n": {"Int64": 2}}`.
 *
 * For large result sets this materializes the entire JSON blob
 * in memory. Future v2 will add pull-row-by-row accessors; for
 * now this is fine for the common-case query sizes.
 *
 * The returned string is OWNED by the caller and must be freed
 * via [`kglite_free_string`](crate::kglite_free_string). Returns
 * null on serialization failure.
 *
 * # Safety
 *
 * `result` must be null or a live pointer returned by a kglite query
 * function. It must not be freed while this call is running.
 */
 const char *kglite_cypher_result_rows_json(const struct KgliteCypherResult *result);

/**
 * Return execution diagnostics as owned JSON, including actual retrieval routes.
 * A live result with no diagnostics returns the JSON string `null`. A null
 * handle or serialization failure returns a null pointer. Free the returned
 * string with [`kglite_free_string`](crate::kglite_free_string); its lifetime
 * is independent of the result handle.
 *
 * # Safety
 * `result` must be null or a live result pointer, and must not be freed during this call.
 */
 const char *kglite_cypher_result_diagnostics_json(const struct KgliteCypherResult *result);

/**
 * Return the number of rows in the result. Useful for callers
 * that want to size buffers before requesting the JSON blob.
 *
 * # Safety
 *
 * `result` must be null or a live pointer returned by a kglite query
 * function. It must not be freed while this call is running.
 */
 uintptr_t kglite_cypher_result_row_count(const struct KgliteCypherResult *result);

/**
 * Free a result handle. Idempotent on null (no-op).
 *
 * # Safety
 *
 * `result` must be either null or a valid pointer previously
 * returned by [`kglite_session_execute_read`](crate::kglite_session_execute_read)
 * or [`kglite_session_execute_mut`](crate::kglite_session_execute_mut)
 * and not yet freed.
 */
 void kglite_cypher_result_free(struct KgliteCypherResult *result);

/**
 * Install a declarative schema on the session's graph.
 *
 * `schema_json` is a JSON object in the one schema dialect kglite speaks —
 * the same one the Python wheel's `define_schema` takes, parsed by the same
 * core function:
 *
 * ```json
 * {
 *   "nodes": {
 *     "Person": {
 *       "required":       ["id", "name"],
 *       "optional":       ["email"],
 *       "types":          {"id": "integer", "name": "string"},
 *       "primary_key":    "id",
 *       "unique":         [["email"]],
 *       "layer":          "managed",
 *       "auto_timestamp": true
 *     }
 *   },
 *   "connections": {
 *     "KNOWS": {
 *       "source":              "Person",
 *       "target":              "Person",
 *       "cardinality":         "many-to-many",
 *       "required_properties": ["since"],
 *       "property_types":      {"since": "integer"}
 *     }
 *   }
 * }
 * ```
 *
 * `source` and `target` are the only mandatory keys anywhere; an absent
 * `nodes` or `connections` section is a no-op, so a document may declare
 * either half alone.
 *
 * `mode` (may be null) is `"merge"` or `"replace"`; null means `"merge"`.
 * **Merge** scopes the declaration to the types the document names — every
 * other type keeps its constraints. **Replace** makes this document the whole
 * schema, so every type it does not name *stops being enforced*. The Python
 * wrapper emits a warning naming each constraint a replace withdraws; C has no
 * warning channel, so pass `"replace"` only when withdrawing is the intent.
 *
 * Installing a schema installs the UNIQUE / NODE KEY constraints it declares,
 * so the call fails when data already in the graph violates one. In that case
 * **nothing changes** — neither the schema nor the indexes — and the caller
 * can fix the data and retry.
 *
 * # Errors
 *
 * - `KGLITE_ERR_NULL_POINTER` — `session` or `schema_json` is null.
 * - `KGLITE_ERR_INVALID_UTF8` — `schema_json` is not valid UTF-8.
 * - `KGLITE_ERR_INVALID_ARGUMENT` — the JSON did not parse, the document is
 *   not in the dialect above, or `mode` is not `"merge"` / `"replace"`; the
 *   message says which.
 * - A constraint status (`KGLITE_ERR_CONSTRAINT_VIOLATION` and friends) when
 *   existing data violates a declared constraint; the message names it.
 *
 * **The schema is not durable until saved.** Call
 * [`kglite_session_save`](crate::kglite_session_save) to persist it.
 *
 * # Safety
 *
 * `session` must be a valid handle from
 * [`kglite_session_new`](crate::kglite_session_new). `schema_json` must be a
 * null-terminated UTF-8 string; `mode` null or the same. `out_error_msg` must
 * be null or a valid writable slot.
 */

KgliteStatusCode kglite_define_schema(struct KgliteSession *session,
                                      const char *schema_json,
                                      const char *mode,
                                      const char **out_error_msg);

/**
 * Create a new session from a graph handle. The session takes
 * ownership of the graph — the caller MUST NOT call
 * [`kglite_graph_free`](crate::kglite_graph_free) on the handle
 * after this call. Free the session via
 * [`kglite_session_free`] when done.
 *
 * # Arguments
 *
 * - `graph` (in, MOVED on success): graph handle. After a successful
 *   call the pointer is no longer valid for any other use.
 * - `out_session` (out, owned): set to the session handle on
 *   success; caller must free via [`kglite_session_free`].
 *
 * # Errors
 *
 * - `KGLITE_ERR_NULL_POINTER` — `graph` or `out_session` is null
 *
 * **The graph handle is consumed only on `Ok`; on any error the caller
 * retains ownership and must still free it** with
 * [`kglite_graph_free`](crate::kglite_graph_free). The move happens after
 * argument validation, so a rejected call leaves the handle exactly as it
 * was — a binding that treats "moved" as unconditional leaks the graph on
 * every failed session open. Unlike the rest of the fallible surface this
 * takes no `out_error_msg`: the sole failure is a null argument, which has
 * no message beyond the code, and the parameter list is frozen for this ABI
 * major version.
 *
 * # Safety
 *
 * `graph` must be a valid `*mut KgliteGraph` previously returned
 * by [`kglite_load_file`](crate::kglite_load_file) and not yet
 * freed or moved into another session. `out_session` must be a
 * valid writable pointer to a `*mut KgliteSession` slot.
 */
 KgliteStatusCode kglite_session_new(struct KgliteGraph *graph, struct KgliteSession **out_session);

/**
 * Run a read-only Cypher query.
 *
 * # Arguments
 *
 * - `session` (in, borrowed): the session.
 * - `query` (in, borrowed): UTF-8 Cypher query, null-terminated.
 * - `params_json` (in, borrowed, may be null): JSON object of
 *   parameter bindings. Pass null or `"{}"` for no params.
 * - `out_result` (out, owned): on success, set to the result
 *   handle; caller must free via [`kglite_cypher_result_free`].
 * - `out_error_msg` (out, owned, may be null): on failure, set
 *   to the error message; caller must free via
 *   [`kglite_free_string`](crate::kglite_free_string).
 *
 * # Errors
 *
 * Any `KgErrorCode` variant — Cypher syntax / type mismatch /
 * timeout / execution error / node-not-found / argument
 * validation. The error message describes the specific failure.
 *
 * # Safety
 *
 * `session` must be valid. `query` and (if non-null) `params_json`
 * must be null-terminated UTF-8 strings.
 */

KgliteStatusCode kglite_session_execute_read(const struct KgliteSession *session,
                                             const char *query,
                                             const char *params_json,
                                             struct KgliteCypherResult **out_result,
                                             const char **out_error_msg);

/**
 * Run a read-only Cypher query with execution options. Same as
 * [`kglite_session_execute_read`], plus:
 *
 * - `timeout_ms`: past this wall-clock budget the query returns
 *   `CypherTimeout`. `0` = no deadline.
 * - `max_work_units`: work budget for the query, **not** a result-row cap.
 *   It is charged against intermediate rows, retained collection items and
 *   scan work — every quantity the executor holds or walks on the way to an
 *   answer — so the count can far exceed the rows returned. Exceeding it
 *   fails the query with an error; nothing is ever silently truncated to it.
 *   Add a `LIMIT` clause to bound output. `0` = no explicit budget.
 *
 * # Safety
 *
 * Same as [`kglite_session_execute_read`].
 */

KgliteStatusCode kglite_session_execute_read_opts(const struct KgliteSession *session,
                                                  const char *query,
                                                  const char *params_json,
                                                  uint64_t timeout_ms,
                                                  uint64_t max_work_units,
                                                  struct KgliteCypherResult **out_result,
                                                  const char **out_error_msg);

/**
 * Run a mutating Cypher query. Same shape as
 * [`kglite_session_execute_read`] but accepts CREATE / SET /
 * DELETE / REMOVE / MERGE statements. The session's underlying
 * graph is auto-committed after a successful execute (no
 * explicit begin/commit in v1 — explicit transactions land in
 * a future ABI version once a binding needs them).
 *
 * # Safety
 *
 * Same as [`kglite_session_execute_read`] except `session` is
 * declared as `*mut` (the call mutates the session's interior
 * graph via commit-swap).
 */

KgliteStatusCode kglite_session_execute_mut(struct KgliteSession *session,
                                            const char *query,
                                            const char *params_json,
                                            struct KgliteCypherResult **out_result,
                                            const char **out_error_msg);

/**
 * Run a mutating query with the same timeout and work-budget semantics as
 * [`kglite_session_execute_read_opts`] — `max_work_units` is a work budget
 * that errors when exceeded, not a result-row cap. A budget failure rolls
 * back the complete statement. `0` disables the corresponding option.
 *
 * # Safety
 *
 * Same as [`kglite_session_execute_mut`].
 */

KgliteStatusCode kglite_session_execute_mut_opts(struct KgliteSession *session,
                                                 const char *query,
                                                 const char *params_json,
                                                 uint64_t timeout_ms,
                                                 uint64_t max_work_units,
                                                 struct KgliteCypherResult **out_result,
                                                 const char **out_error_msg);

/**
 * Run several read-only Cypher queries against a single consistent
 * snapshot, in one lock acquisition.
 *
 * `queries_json` is a JSON array of objects, each `{"query": "...",
 * "params": {...}}` (the `params` key is optional). Every query sees
 * the same snapshot, taken once up front — cheaper and more consistent
 * than N separate [`kglite_session_execute_read`] calls when a binding
 * issues many small reads.
 *
 * On success `out_results_json` is set to an owned JSON string: an
 * array of `{"columns": [...], "rows": [{...}], "diagnostics": {...}}` objects, one per input
 * query in order, with the same natural-value encoding as
 * [`kglite_cypher_result_rows_json`]. Free it with
 * [`kglite_free_string`](crate::kglite_free_string).
 *
 * The batch aborts on the first failing query: `out_results_json` is
 * set to null and the status code / `out_error_msg` describe that
 * query's failure.
 *
 * # Safety
 *
 * `session` must be valid; `queries_json` a null-terminated UTF-8 JSON
 * array; `out_results_json` a valid writable `*const c_char` slot;
 * `out_error_msg` null or a valid writable slot.
 */

KgliteStatusCode kglite_session_execute_read_batch(const struct KgliteSession *session,
                                                   const char *queries_json,
                                                   const char **out_results_json,
                                                   const char **out_error_msg);

/**
 * Run several mutating Cypher queries in a single transaction — one
 * `begin`, N executes (each sees the previous query's writes), a single
 * `commit`. The batch is **atomic**: if any query fails, the
 * transaction is dropped uncommitted and none of the batch's mutations
 * reach the graph.
 *
 * `queries_json` / `out_results_json` have the same shape as
 * [`kglite_session_execute_read_batch`]. On failure `out_results_json`
 * is null and the status / `out_error_msg` describe the failing query.
 *
 * # Safety
 *
 * Same as [`kglite_session_execute_read_batch`] except `session` is
 * `*mut` (the call mutates the session's interior graph via
 * commit-swap).
 */

KgliteStatusCode kglite_session_execute_mut_batch(struct KgliteSession *session,
                                                  const char *queries_json,
                                                  const char **out_results_json,
                                                  const char **out_error_msg);

/**
 * Bulk-create edges addressed by **stable node id + type**, bypassing
 * Cypher — the fast ingest path for bindings loading many edges.
 *
 * `edges_json` is a JSON array of objects:
 * `{"src_id": <id>, "src_type": "Person", "dst_id": <id>,
 *   "dst_type": "Company", "type": "WORKS_AT", "props": {...}}`
 * (`props` optional). `src_id`/`dst_id` are the nodes' stable ids (the
 * same value `n.id` returns), not internal indices. Runs in one
 * transaction: the whole batch commits together, or — on error — none
 * of it lands. Endpoints must already exist; an edge whose source or
 * target id isn't found for its declared type is skipped and counted.
 *
 * On success `out_report_json` is set to an owned JSON object
 * `{"connections_created": N, "skipped_missing_endpoint": M}`; free it
 * with [`kglite_free_string`](crate::kglite_free_string).
 *
 * This wraps the shared core primitive
 * [`add_edges_from_specs`](kglite::api::mutation::add_edges_from_specs) —
 * the same engine the Python `add_connections` DataFrame path uses.
 *
 * # Safety
 *
 * `session` must be valid; `edges_json` a null-terminated UTF-8 JSON
 * array; `out_report_json` a valid writable `*const c_char` slot;
 * `out_error_msg` null or a valid writable slot.
 */

KgliteStatusCode kglite_create_edges_batch(struct KgliteSession *session,
                                           const char *edges_json,
                                           const char **out_report_json,
                                           const char **out_error_msg);

/**
 * Checkpoint a session's graph to `path` — the save half of the
 * open / mutate / save cycle.
 *
 * [`kglite_session_new`] takes ownership of the graph handle, so a graph
 * mutated through
 * [`kglite_session_execute_mut`](crate::kglite_session_execute_mut) can only
 * be persisted from the session that now holds it; this is that call.
 * [`kglite_save_graph`](crate::kglite_save_graph) remains the entry point
 * for a graph handle that has *not* been moved into a session.
 *
 * **The lease contract: a caller that saves must hold the writer lease
 * across the whole open / mutate / save interval, not merely at this call.**
 * Take it with
 * [`kglite_writer_lease_acquire`](crate::kglite_writer_lease_acquire) before
 * opening, free it after saving. Two processes that both open one path, both
 * mutate, and both save each write a complete snapshot and the later one
 * wins outright and silently — locking only at save time is already too late
 * to notice. Read-only sessions take no lease.
 *
 * The save writes through the session's own graph, so it never copies the
 * graph to checkpoint it, and it is serialized against concurrent
 * `execute_mut` calls on the same session: the file is a consistent
 * point-in-time image. Readers holding a result from before the save are
 * unaffected.
 *
 * `fsync` != 0 is the durable default: atomic temp+rename plus a file and
 * parent-directory flush, so the checkpoint survives power loss. `fsync` ==
 * 0 is the fast, **non-durable** opt-out — still never a torn file, but the
 * bytes may not survive an OS crash. The storage mode is written from the
 * graph being saved, so reopening with
 * [`kglite_open_or_create_graph_in_mode`](crate::kglite_open_or_create_graph_in_mode)
 * and a null mode brings the graph back in the mode it was saved in.
 *
 * # Errors
 *
 * - `KGLITE_ERR_NULL_POINTER` — `session` or `path` is null
 * - `KGLITE_ERR_INVALID_UTF8` — `path` isn't valid UTF-8
 * - `KGLITE_ERR_FILE_IO` — the write failed
 *
 * # Safety
 *
 * `session` must be a valid handle from [`kglite_session_new`], not yet
 * freed; `path` a null-terminated UTF-8 string; `out_error_msg` null or a
 * valid writable slot.
 */

KgliteStatusCode kglite_session_save(struct KgliteSession *session,
                                     const char *path,
                                     uint8_t fsync,
                                     const char **out_error_msg);

/**
 * Free a session handle. Idempotent on null (no-op).
 *
 * # Safety
 *
 * `session` must be either null or a valid pointer previously
 * returned by [`kglite_session_new`] and not yet freed.
 */
 void kglite_session_free(struct KgliteSession *session);

/**
 * Return the canonical human-readable name of a status code (e.g.
 * `"CypherSyntax"`, `"NodeNotFound"`, `"InvalidUtf8"`).
 *
 * The returned string is OWNED by the caller and must be freed
 * via [`kglite_free_string`](crate::kglite_free_string). Returns
 * null on `Ok` (no error to name).
 */
 const char *kglite_status_code_name(KgliteStatusCode code);

/**
 * Return the canonical name of a status code as a **static** string — the
 * allocation-free companion to [`kglite_status_code_name`].
 *
 * Same text (`"CypherSyntax"`, `"NodeNotFound"`, `"InvalidUtf8"`, …) and the
 * same null on `Ok`, but the pointer is a `'static` constant in the library's
 * own read-only data rather than a fresh heap copy.
 *
 * **Do NOT free the returned pointer.** Handing it to
 * [`kglite_free_string`](crate::kglite_free_string) is undefined behaviour —
 * it is not allocator-owned memory. That is the whole difference between the
 * two functions, so pick one per call site and do not mix them:
 * [`kglite_status_code_name`] for a caller that would rather free one uniform
 * kind of string, this one for a binding that names a code on every error
 * (the common case — the name goes straight into the exception it raises),
 * which then skips the allocate/copy/free round trip entirely.
 *
 * Added rather than changing [`kglite_status_code_name`] in place: that
 * function shipped with owned-string semantics and this ABI is additive-only
 * within a major version, so silently flipping who frees it would turn a
 * correct caller into a double-free.
 *
 * The table is exhaustive over `KgliteStatusCode` by construction (no
 * wildcard arm), so a newly added status code is a compile error here rather
 * than a silently unnamed one.
 */
 const char *kglite_status_code_name_static(KgliteStatusCode code);

/**
 * Return the Neo4j wire status code for a status code (e.g.
 * `"Neo.ClientError.Statement.SyntaxError"`). Useful for bindings
 * implementing the Neo4j Bolt wire protocol or compatible HTTP
 * APIs.
 *
 * The returned string is OWNED by the caller and must be freed
 * via [`kglite_free_string`](crate::kglite_free_string). Returns
 * null on `Ok` or on C-ABI-only error codes that have no Neo4j
 * counterpart (`InvalidUtf8`, `NullPointer`).
 */
 const char *kglite_status_code_neo4j_status(KgliteStatusCode code);

/**
 * Return the HTTP status code mapping for a status code (e.g.
 * 400 for `CypherSyntax`, 404 for `NodeNotFound`, 500 for
 * `Internal`). Useful for REST/gRPC bindings.
 *
 * Returns 0 for `Ok` and 500 for C-ABI-only codes (`InvalidUtf8`
 * = 400 / bad request from caller, `NullPointer` = 400,
 * `WriterLeaseHeld` = 409 / conflict, retriable as-is — the same
 * mapping core gives `TransactionConflict`, the other lost-race code).
 */
 uint16_t kglite_status_code_http_status(KgliteStatusCode code);

/**
 * Free a string previously returned by any `kglite_*` function.
 *
 * # Safety
 *
 * `s` must be either null or a pointer previously returned
 * by a `kglite_*` function (these all flow through
 * [`alloc_c_string`]). Calling twice on the same pointer is UB.
 * Calling with a pointer to a string allocated by the C caller's
 * own `malloc` is UB.
 *
 * Passing null is safe (treated as a no-op).
 *
 * # Examples
 *
 * ```c
 * const char* col_json = kglite_cypher_result_columns_json(result);
 * printf("%s\n", col_json);
 * kglite_free_string(col_json);
 * ```
 */
 void kglite_free_string(const char *s);

/**
 * Build a BM25 lexical index over `node_type`'s `property`, for keyword
 * ranking in Cypher.
 *
 * Wraps [`kglite::api::text_indexes::build_text_index`]. Opt-in and explicit.
 * The index does not follow later writes eagerly: it records them and folds
 * them in at query time while the outstanding delta stays under the default
 * auto-refresh limit, and once past it a rebuild — this call again — is the
 * route back. `SHOW INDEXES` reports the delta. Deleting a node prunes its
 * document immediately (a freed node slot is reused, and an orphaned document
 * would be inherited by its next owner); `vacuum` renumbers every node and
 * therefore drops text indexes wholesale. Strings and lists containing only
 * strings/nulls each form one document; list members are space-separated and
 * null members ignored. Empty strings and empty/all-null lists are empty
 * documents. Absent values, other types, or any non-text/non-null list member
 * skip the whole document and count in the report. Fields use the same alias
 * resolution a `MATCH` filter uses.
 *
 * The auto-refresh limit is not a parameter here: this signature is published
 * and additive-only within the ABI major, so the C route takes the default and
 * a future symbol carries the override if one is ever asked for.
 *
 * On success `out_report_json` is an owned JSON object
 * `{"indexed": N, "skipped": S, "terms": T}`; free it with
 * [`kglite_free_string`](crate::kglite_free_string).
 *
 * # Errors
 *
 * - `KGLITE_ERR_NULL_POINTER` — `session`, `node_type`, `property`, or
 *   `out_report_json` is null.
 * - `KGLITE_ERR_INVALID_UTF8` — a string argument is not valid UTF-8.
 * - `KGLITE_ERR_INVALID_ARGUMENT` — the node type is unknown, the graph is
 *   disk-backed (the index is heap-resident, so disk mode refuses), or the
 *   type has nodes and none of them carries a string for `property`; the
 *   message explains which.
 *
 * # Safety
 *
 * `session` must be a valid handle from
 * [`kglite_session_new`](crate::kglite_session_new). `node_type` and
 * `property` must be null-terminated UTF-8 strings. `out_report_json` must be
 * a valid writable slot; `out_error_msg` null or a valid writable slot.
 */

KgliteStatusCode kglite_session_build_text_index(struct KgliteSession *session,
                                                 const char *node_type,
                                                 const char *property,
                                                 const char **out_report_json,
                                                 const char **out_error_msg);

#endif  /* KGLITE_H_INCLUDED */
